x-api-base: &api_base
  build:
    context: .
    dockerfile: api.Dockerfile
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - ./src/python/url_tribunal:/app/url_tribunal
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - url-tribunal-nw

services:
  db:
    image: mysql:8.4.10
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - url-tribunal-nw

  redis:
    image: redis:8.0-alpine3.21
    command: redis-server --appendonly yes
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - url-tribunal-nw

  api:
    <<: *api_base
    image: url-tribunal-api
    container_name: api
    ports:
      - "8000:8000"

  worker:
    <<: *api_base
    image: url-tribunal-worker
    container_name: worker
    command:
      - "celery"
      - "-A"
      - "url_tribunal.core.celery"
      - "worker"
      - "-l"
      - "INFO"
      - "--pool=threads"
      - "--concurrency=${CELERY_CONCURRENCY:-8}"

  flower:
    image: mher/flower:2.0
    container_name: flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_FLOWER_USER: ${CELERY_FLOWER_USER}
      CELERY_FLOWER_PASSWORD: ${CELERY_FLOWER_PASSWORD}
    command:
      - "celery"
      - "--broker=${CELERY_BROKER_URL}"
      - "flower"
      - "--port=5555"
      - "--basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
      - "--persistent=true"
      - "--db=/data/flower.db"
    volumes:
      - flower_data:/data
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - url-tribunal-nw

volumes:
  db_data:
  redis_data:
  flower_data:

networks:
  url-tribunal-nw:
    driver: bridge