COMPOSE := docker compose -f docker-compose.yml
API_SERVICE := api
ALEMBIC_INI := ../etc/alembic.ini

.PHONY: build up down down-v test lint format revision migrate downgrade

build:
	${COMPOSE} up --build -d --remove-orphans

up:
	${COMPOSE} up -d

down:
	${COMPOSE} down

down-v:
	${COMPOSE} down -v

test:
	pytest

lint:
	ruff check .

format:
	ruff format . --diff

revision:
	@$(eval m ?= 'autogenerated_revision')
	${COMPOSE} exec ${API_SERVICE} alembic -c ${ALEMBIC_INI} revision --autogenerate -m "$(m)"

upgrade:
	${COMPOSE} exec ${API_SERVICE} alembic -c ${ALEMBIC_INI} upgrade head

downgrade:
	${COMPOSE} exec ${API_SERVICE} alembic -c ${ALEMBIC_INI} downgrade -1
