"""add domain, url, scan and provider scan tables

Revision ID: 1fa03da559b6
Revises: 
Create Date: 2026-06-23 09:13:37.912236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1fa03da559b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'domain',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fqdn', sa.String(length=255), nullable=False),
        sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', 'unknown', name='verdict'), server_default='unknown',
                  nullable=False),
        sa.Column('verdict_confidence', sa.Float(precision=2), server_default=sa.text('0.0'),
                  nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('fqdn'),
    )
    op.create_table(
        'url',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('domain_id', sa.Integer(), nullable=False),
        sa.Column('url_hash', sa.String(length=64), nullable=False),
        sa.Column('full_url', sa.Text(), nullable=False),
        sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', 'unknown', name='verdict'), server_default='unknown',
                  nullable=False),
        sa.Column('verdict_confidence', sa.Float(precision=2), server_default=sa.text('0.0'),
                  nullable=False),
        sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url_hash'),
    )
    op.create_table(
        'scan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url_id', sa.Integer(), nullable=False),
        sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['url_id'], ['url.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('url_id_scanned_at_idx', 'scan', ['url_id', sa.literal_column('scanned_at DESC')], unique=False)
    op.create_table(
        'provider_scan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('scan_id', sa.Integer(), nullable=False),
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', 'unknown', name='verdict'), server_default='unknown',
                  nullable=False),
        sa.Column('response', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_scan')
    op.drop_index('url_id_scanned_at_idx', table_name='scan')
    op.drop_table('scan')
    op.drop_table('url')
    op.drop_table('domain')
    # ### end Alembic commands ###
