"""Create domain, url and url_scan tables

Revision ID: 55640fe53655
Revises: 
Create Date: 2026-06-19 12:50:06.263556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55640fe53655'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', 'unknown', name='verdict'), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fqdn')
    )
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('full_url', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', 'unknown', name='verdict'), server_default='unknown', nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_table('url_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_scan')
    op.drop_table('url')
    op.drop_table('domain')
    # ### end Alembic commands ###
