"""add last_scan_id FK

Revision ID: 5e084c3836c2
Revises: 1fa03da559b6
Create Date: 2026-07-02 16:53:11.016854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5e084c3836c2'
down_revision: Union[str, Sequence[str], None] = '1fa03da559b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('last_scan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'url', 'scan', ['last_scan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='foreignkey')
    op.drop_column('url', 'last_scan_id')
    # ### end Alembic commands ###
